name: Kastemaa
favicon: null
layout_spectrum: 0.5058821758721024
typography_spectrum: 0.14195997337810695
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#ffffff'
    - '#b5b5b5'
    - '#a47138'
    - '#49403b'
  brandStrength: 0.5430189808830619
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5416129992809147
purpose: []
