name: Kastemaa
favicon: null
layout_spectrum: 0.5058821758721024
typography_spectrum: 0.14195997337810695
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5430189808830619
  lightness: 0.5909679948817939
  saturation: 0.11566308583132923
  rhythmicContrast: 0.5416129992809147
purpose: []
